# \u2699\ufe0f PORT (Render fournit automatiquement)
server.port=${PORT:8080}
server.error.whitelabel.enabled=false
spring.main.banner-mode=console

# \ud83d\udcbe MySQL / Railway
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \ud83e\udde9 JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# \ud83e\udde0 Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.web=INFO
logging.level.com.transfertapi=DEBUG